CREATE VIEW Countries AS SELECT * FROM COUNTRY;

CREATE VIEW Events AS SELECT * FROM EVENT;

CREATE VIEW Foods AS SELECT * FROM FOOD;

CREATE VIEW Musics AS SELECT * FROM MUSIC;

CREATE VIEW Persons AS SELECT * FROM PERSON;

CREATE VIEW Places AS SELECT * FROM PLACE;

CREATE VIEW Sports AS SELECT * FROM SPORT;